n_epoch: 130
# scheduler: 'OneCycleLR'
scheduler: 'Cosine'

batch_size: 96

# previous values was 16
crop_pad_size: 0
# no resize
image_size: [137, 236]
# moderate scal factor
aug_scale: [-0.05, 0.05]
