n_epoch: 90
fold: 0

scheduler: 'Adam'
lr: 0.00001
batch_size: 256

fold: 0
use_class_weight: False

aug_cutmix_p:  0.5
aug_mixup_p: 0.5

# previous values was 16
crop_pad_size: 0
# no resize
image_size: [64, 64]
# moderate scal factor
aug_scale: [-0.05, 0.05]
aug_rot: 7
aug_shear: 10
aug_morph: 0.3
