n_epoch: 140
fold: 0

scheduler: 'Cosine'
lr: 0.00002
batch_size: 128
weight_decay: 0.0001

fold: 0
use_class_weight: False

aug_cutmix_p:  0.5
aug_cutmix_alpha: 1.
aug_mixup_p: 0.5
aug_mixup_alpha: 0.8

aug_gridmask_p: 0.5

# previous values was 16
crop_pad_size: 0
# no resize
image_size: [128, 128]
# moderate scal factor
aug_scale: [-0.05, 0.05]
aug_rot: 10
aug_shear: 5
aug_morph: 0.3
aug_auto_contrast_p: 0.5
