n_epoch: 120
fold: 0

### MODEL, OPTIM
model_name: 'se_resnext101_32x4d'

scheduler: 'Cosine'
lr: 0.00002
batch_size: 128
weight_decay: 0

use_class_weight: False

### PREPROCESS,
crop_pad_size: 0
image_size: [128, 128]

### AUGMENTATION
aug_cutmix_p:  0.5
aug_cutmix_alpha: 1.
aug_mixup_p: 0.5
aug_mixup_alpha: 0.8

aug_gridmask_p: 0.5

### BASIC AUGMENTATION
aug_scale: [-0.05, 0.05]
aug_rot: 10
aug_shear: 5
aug_morph: 0.3
aug_auto_contrast_p: 0.5

