n_epoch: 90
fold: 3
num_workers: 4

# model_name: 'resnet34'
model_name: 'seresnext50_dropblock_surgery'
aug_gridmask_p: 0.0
use_pretrain: true
weight_decay: 0.00001

scheduler: 'CosineWarm'  # 1e-4 ~ 1e-6
# lr: 0.00002
# lr: 0.000005
### batch_size: 128
batch_size: 48

use_class_weight: False



# AUG

aug_cutmix_p:  0.0
aug_cutmix_alpha: 1.
aug_mixup_p: 0.0
aug_mixup_alpha: 0.8

# PREPROCESS
crop: false
crop_pad_size: 0  # valid when crop is true
image_size: [128, 128]

# AUG
aug_scale: [-0.05, 0.05]  # moderate scal factor
aug_rot: 10
aug_shear: 5
aug_morph: 0.3
aug_auto_contrast_p: 0.5
